# Generated by Django 6.0.4 on 2026-04-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzili')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan'), ('archived', 'Arxivlangan')], default='new', max_length=20, verbose_name='Holati')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahorat nomi')),
                ('level', models.PositiveIntegerField(help_text='0 dan 100 gacha qiymat kiriting', verbose_name='Daraja (%)')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', "Ma'lumotlar bazasi"), ('devops', 'DevOps'), ('tools', 'Vositalar'), ('other', 'Boshqa')], default='backend', max_length=20, verbose_name='Kategoriya')),
                ('icon', models.CharField(blank=True, help_text='devicon yoki fa class nomi', max_length=100, verbose_name='Icon nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Mahorat',
                'verbose_name_plural': 'Mahoratlar',
                'ordering': ['category', 'order', '-level'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Texnologiya nomi')),
                ('color', models.CharField(default='indigo', help_text='Tailwind rang nomi: indigo, emerald, rose, amber, sky, etc.', max_length=20, verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(verbose_name='Qisqa tavsif')),
                ('detailed_description', models.TextField(blank=True, help_text="Loyiha haqida to'liq ma'lumot", verbose_name='Batafsil tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Loyiha rasmi')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub linki')),
                ('demo_link', models.URLField(blank=True, verbose_name='Demo linki')),
                ('status', models.CharField(choices=[('completed', 'Tugallangan'), ('in_progress', 'Jarayonda'), ('archived', 'Arxivlangan')], default='completed', max_length=20, verbose_name='Holati')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured (Asosiy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.tag', verbose_name='Texnologiyalar')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
